//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTS.Applens.WorkProfiler.DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UtilityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilityResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTS.Applens.WorkProfiler.DAL.UtilityResource", typeof(UtilityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DART_Debt_with_rules.R.
        /// </summary>
        internal static string ClassificationMapperClass {
            get {
                return ResourceManager.GetString("ClassificationMapperClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Krishna/Ela/DART_Debt_with_rules.R.
        /// </summary>
        internal static string ClassificationMapperFile {
            get {
                return ResourceManager.GetString("ClassificationMapperFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.223.69.37.
        /// </summary>
        internal static string DataLakeInfraIP {
            get {
                return ResourceManager.GetString("DataLakeInfraIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.142.174.203.
        /// </summary>
        internal static string DataLakeIP {
            get {
                return ResourceManager.GetString("DataLakeIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50070.
        /// </summary>
        internal static string DataLakePort {
            get {
                return ResourceManager.GetString("DataLakePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hadoop.
        /// </summary>
        internal static string DataLakeUsername {
            get {
                return ResourceManager.GetString("DataLakeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classified&amp;Prediction.csv.
        /// </summary>
        internal static string DebtAnalyticsReportExcel {
            get {
                return ResourceManager.GetString("DebtAnalyticsReportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file format is not supported.Please upload valid file..
        /// </summary>
        internal static string ER1001 {
            get {
                return ResourceManager.GetString("ER1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file uploaded is password protected. Please upload valid file..
        /// </summary>
        internal static string ER1002 {
            get {
                return ResourceManager.GetString("ER1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapped columns cannot contain empty/null values. Please upload valid file..
        /// </summary>
        internal static string ER1003 {
            get {
                return ResourceManager.GetString("ER1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uploaded Classification file does not match with the Sampling file. Please upload correct file to proceed with Auto Classification.
        /// </summary>
        internal static string ER1004 {
            get {
                return ResourceManager.GetString("ER1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excel work sheets are not having identical columns. Please upload valid files..
        /// </summary>
        internal static string ER1005 {
            get {
                return ResourceManager.GetString("ER1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File - WorkSheets is empty or with no rows. Please upload valid file..
        /// </summary>
        internal static string ER1006 {
            get {
                return ResourceManager.GetString("ER1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DART_Debt_Sampling.R.
        /// </summary>
        internal static string MapReduceMapperClass {
            get {
                return ResourceManager.GetString("MapReduceMapperClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Krishna/Ela/DART_Debt_Sampling.R.
        /// </summary>
        internal static string MapReduceMapperFile {
            get {
                return ResourceManager.GetString("MapReduceMapperFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /streamJob/tempout/Output_.
        /// </summary>
        internal static string MapReduceMapperOutputPath {
            get {
                return ResourceManager.GetString("MapReduceMapperOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlsx,.xls,.csv,.zip.
        /// </summary>
        internal static string ValidFileExtensions {
            get {
                return ResourceManager.GetString("ValidFileExtensions", resourceCulture);
            }
        }
    }
}
